### ISSUE TITLE
cannot load such file -- liquid-md5

### ISSUE THREAD

**Issue by NathanHazout** [pathawks/liquid-md5#2]
I edited the config.yml file with:

```
gems:
  - liquid-md5
```

I added this to my Gemfile:

```
gem 'liquid-md5'
```

Yet when trying to build with Jekyll I get:

```
/Users/nathanh/.rvm/gems/ruby-2.2.4/gems/jekyll-3.0.2/lib/jekyll/plugin_manager.rb:30:in `require': cannot load such file -- liquid-md5 (LoadError)
    from /Users/nathanh/.rvm/gems/ruby-2.2.4/gems/jekyll-3.0.2/lib/jekyll/plugin_manager.rb:30:in `block in require_gems'
    from /Users/nathanh/.rvm/gems/ruby-2.2.4/gems/jekyll-3.0.2/lib/jekyll/plugin_manager.rb:27:in `each'
    from /Users/nathanh/.rvm/gems/ruby-2.2.4/gems/jekyll-3.0.2/lib/jekyll/plugin_manager.rb:27:in `require_gems'
    from /Users/nathanh/.rvm/gems/ruby-2.2.4/gems/jekyll-3.0.2/lib/jekyll/plugin_manager.rb:19:in `conscientious_require'
    from /Users/nathanh/.rvm/gems/ruby-2.2.4/gems/jekyll-3.0.2/lib/jekyll/site.rb:97:in `setup'
    from /Users/nathanh/.rvm/gems/ruby-2.2.4/gems/jekyll-3.0.2/lib/jekyll/site.rb:49:in `initialize'
    from /Users/nathanh/.rvm/gems/ruby-2.2.4/gems/jekyll-3.0.2/lib/jekyll/commands/build.rb:30:in `new'
    from /Users/nathanh/.rvm/gems/ruby-2.2.4/gems/jekyll-3.0.2/lib/jekyll/commands/build.rb:30:in `process'
    from /Users/nathanh/.rvm/gems/ruby-2.2.4/gems/jekyll-3.0.2/lib/jekyll/commands/serve.rb:26:in `block (2 levels) in init_with_program'
    from /Users/nathanh/.rvm/gems/ruby-2.2.4/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
    from /Users/nathanh/.rvm/gems/ruby-2.2.4/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
    from /Users/nathanh/.rvm/gems/ruby-2.2.4/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
    from /Users/nathanh/.rvm/gems/ruby-2.2.4/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
    from /Users/nathanh/.rvm/gems/ruby-2.2.4/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
    from /Users/nathanh/.rvm/gems/ruby-2.2.4/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
    from /Users/nathanh/.rvm/gems/ruby-2.2.4/gems/jekyll-3.0.2/bin/jekyll:17:in `<top (required)>'
    from /Users/nathanh/.rvm/gems/ruby-2.2.4/bin/jekyll:23:in `load'
    from /Users/nathanh/.rvm/gems/ruby-2.2.4/bin/jekyll:23:in `<main>'
    from /Users/nathanh/.rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:15:in `eval'
    from /Users/nathanh/.rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by DirtyF** [comment]
@pathawks same problem here, when I add 'liquid-md5' to `_config.yml`: 

```
bundle exec jekyll build
Configuration file: /Users/frank/code/sudweb/2016/_config.yml
Configuration file: /Users/frank/code/sudweb/2016/_config.yml
  Dependency Error: Yikes! It looks like you don't have liquid-md5 or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- liquid-md5' If you run into trouble, you can find helpful resources at http://jekyllrb.com/help/!
jekyll 3.1.3 | Error:  liquid-md5
```

I checked the gem dependencies, I have bundle, rake and bundler latest versions.

**Comment by maxmumford** [comment]
Yep, same problem here too. Temporary solution:
- create directory _plugins in your root
- create file _plugins/md5.rb
- paste the contents of [this file](https://raw.githubusercontent.com/pathawks/liquid-md5/master/lib/md5.rb)

Max

**Comment by pathawks** [comment]
Sorry, the file had the wrong name.

This has been fixed, and a new Gem has been pushed :+1:
